stages:
  - test
  - build 
  - deploy
#
lint:
  image: rust:1.23.0
  stage: test
  script:
    - rustup component add rustfmt-preview
    - cargo fmt -- --error-on-unformatted --unstable-features
#
install:
  image: rust:1.23.0
  stage: build
  script:
    - rustup component add --toolchain beta rustfmt-preview
    - cargo build --release
  artifacts:
    paths:
      - target/release/gitall