stages:
  - test
  - build 
  - deploy
#
install:
  image: rust:1.23.0
  stage: build
  script:
    - rustup component add --toolchain beta rustfmt-preview
    - cargo build --release
  artifacts:
    paths:
      - target/release/gitall