name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run help
      run: ./target/release/projectsctl --help
    - name: Run add
      run: ./target/release/projectsctl add . --name test
    - name: Run list
      run: ./target/release/projectsctl list
    - name: Run list wide
      run: ./target/release/projectsctl list --wide
    - name: Run remove
      run: ./target/release/projectsctl remove .
    - name: Store executable as artefact
      uses: actions/upload-artifact@v2
      with:
        name: projectsctl-executable
        path: target/release/projectsctl
    - name: Create a tag
      uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GH_CREATE_TAG_TOKEN }}
        version_assertion_command: 'grep -q "version = \"$version\"" Cargo.toml'
        version_tag_prefix: 'v'
